default:	
	gcc -o prog main.c stringWrap.c input.c listArrayList.c listElem.c mapArrayList.c mapElem.c countryLocation.c countryStatistic.c earthquakeData.c clearMemory.c showCommands.c histogram.c countryS.c regionAvg.c listT.c count.c topN.c -lm
clean:
	rm -f prog